export * from './HomePage/HomePage'
export * from './TrendingPage/TrendingPage'
export * from './SearchPage/SearchPage'
export * from './TopRatedPage/TopRatedPage'
export * from './UpcomingPage/UpcomingPage'
export * from './MoviesPage/MoviesPage'
