export * from './movie.interface'
export * from './movieVideo.interface'
export * from './ditailsIntarfaceByMovie'
export * from './castList.interfaceByMovie'
export * from './genres.interface'
export * from './IErrorMovie'
export * from './params.interface'
export * from './auth.interface'